version: '3'
services:
  react_challenge_ui:
    build:
      context: .
    ports:
      - '3000:3000'
    container_name: react_challenge_ui
    stdin_open: true
    volumes:
      - .:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
